### PR TITLE
upgrade mongoid to 2.0.0.rc.7

### PR DESCRIPTION
**Pull request by saberma**
fixed:
1. set_allowed? method was deleted
2. parentize method arguments definition was changed
2. use update_attributes instead of self[]= to update field value

pass all test.

https://github.com/mongoid/mongoid/commit/767dfd41ac0b241c0394a2594da0b83f67f880be#L0L234
https://github.com/mongoid/mongoid/commit/b458c0cee7697fa54e8a0c9a17d9fa47184d1a0c#L18L65

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Thanks! I pushed your changes into master :)

**Comment by kristianmandrup** [comment]
Thanks :) Your changes have been pushed to master

**Comment by volkanunsal** [comment]
I came across this pull request when I googled for an error I have been getting while using acts_as_list_mongoid.

```
 > collection.init_list!
 #=>NoMethodError Exception: undefined method `set_allowed?' for #<Demo::Node:0x000001065d2ff8>
```

Not sure if they are related but my setup seems to be looking for the set_allowed? method, which appears to be removed from the API?

**Comment by kristianmandrup** [comment]
I have released a new version of mongoid_adjust which fixes this error. 
The acts_as_list gem was developed a year ago and might be outdated in some respects. Would be nice with a refactoring, using the latest improvements in mongoid etc. Currently some of the specs fail, be advised. Not sure if it is the implementation or the tests that are to blame.

**Comment by simianarmy** [comment]
Thanks - it worked for me once I was able to figure out how to use the master branch from my Gemfile.  I thought leaving the version out would do it but that must just download the latest version, not master.

**Pull request merged**
